### ISSUE TITLE
grub.version is deprecated

### ISSUE THREAD

**Issue by stites** [voidzero/nixos-zfs-setup#1]
Line https://github.com/voidzero/nixos-zfs-setup/blob/master/nixos-zfs-setup.sh#L238 throws the following deprecation error:

```
trace: warning: The boot.loader.grub.version option does not have any effect anymore, please remove it from your configuration.
```

I'm not sure if you would prefer to do this now or after 23.11, but eventually this will cause a silent error.

As always, a pleasure using this script! thank you.

**Comment by voidzero** [comment]
Ah, good one. Thanks.

**Comment by voidzero** [comment]
Oops, pressed close a bit too quickly, thanks @stites there is no alternative to grub2 so I removed it from the script.
